# place for STATIC settings for release. [autogenerated] 
export kernel_general_version="4.2.6" # base version (should match the one is sourcecode.list)
export KERNEL_DATE='2015-11-12 01:07:44' # UTC time of mempo version. This is > then max(kernel,grsec,patches) times
export CURRENT_SEED='569ac83e2331d6ff7f7ada150346da1616c73e7d2552ca18c7448b1b3cfe66ab' #  block 884971 (*)
export DEBIAN_REVISION='001' # see README.md how to update it on git tag, on rc and final releases
